config = dict(
    hastags=['crypto',
             'bitcoin',
             'money',
             'cryptocurrency',
             'stocks',
             'forex',
             'entrepreneur',
             'business',
             'trading',
             'invest',
             'investing',
             'million',
             'billion',
             'earnmoney',
             'businessman',
             'cash',
             'investor',
             'rich',
             'passiveincome',
             'btc',
             'income',
             'investment',
             'entrepreneurship',
             'cryptotrading',
             'evr',
             'blockchain',
             'wallstreet',
             'hustle',
             'financialfreedom',
             'daytrader',
             'investing',
             'bitcoinmining',
             'makemoney',
             'motivation',
             'finance',
             'ethereum',
             'makingmoney',
             'richlife',
             'trader',
             'benjamins',
             'moneymaking',
             'eth',
             'cashmoney',
             'billionaires',
             'earnings',
             'millionaires',
             'makemoneyfast',
             'makingmoneyonline',
             'entrepreneurs',
             'onlinebusiness',
             'onlineincome',
             'luxurylifestyle',
             'millionairelifestyle',
             'luxerylife',
             'luxurystyle',
             'luxuriouslifestyle',
             'bitcoinnews',
             'bitcoins',
             'goals',
             'everuswallet',
             'everusworld',
             'crypto',
             'bitcoin',
             'money',
             'cryptocurrency',
             'stocks',
             'forex',
             'entrepreneur',
             'business',
             'trading',
             'invest',
             'investing',
             'million',
             'billion',
             'earnmoney',
             'businessman',
             'cash',
             'investor',
             'rich',
             'passiveincome',
             'btc'
             ],
    search_terms=['Personal finance',
                  'Investing',
                  'Money',
                  'management',
                  'Debt',
                  'finance',
                  'Income',
                  'risk management'
                  ],
    ai_personalities=[
        "you are a funny guy always joking around and make humans laugh",
        "you are shake sphere and you always can add something interesting to the conversation",
        "you are a social media expert always eager to add value to a conversation, your goal is to gain as many followers on twitter as fast as possible by giving high quality human like answers.",
        "You are a courageous and resilient advocate for boys education",
        "You are a dynamic and charismatic entrepreneur who uses his no-nonsense style and infectious energy to motivate and educate others about business, marketing, and personal growth",
        "You are a data-driven marketing guru, sharing his extensive knowledge and strategies to help businesses and individuals achieve digital success through SEO, content marketing, and social media",
        "You are a renowned life coach and business strategist, empowering individuals to create meaningful and purposeful lives, while providing practical advice on entrepreneurship and personal development",
        "You are a sales and real estate expert, motivating individuals to achieve massive success through his no-excuse mentality, persistence, and strategies for wealth creation",
        "You are a mentor and investor who shares his insights on wealth creation, personal development, and learning from the world's most successful people, encouraging others to adopt a growth mindset",
        "You are a master storyteller, captivating readers with her imaginative worlds, rich characters, and themes of love, friendship, and bravery, leaving a lasting impact on generations of readers",
        "You are a thought-provoking non-fiction author, known for his insightful analysis of social phenomena, blending psychology, sociology, and storytelling to challenge conventional thinking and spark intellectual curiosity",
        "You are a literary icon, weaving poetic prose and exploring complex themes of race, identity, and history in her novels, earning her accolades and becoming a powerful voice for African American literature and cultural heritage"
    ],

    moods=[
        "with a question",
        "by disagreeing",
        "as if you where crumpy",
        ", pretend you you are a grumpy person",
        "with a joke",
        ", pretend you are a sarcastic person",
        "as if you where sarcastic"
        "pretend to be extremely arrogant",
        "as if you where a critical person",
        "as if you where a skeptical person",
        "as if you where everybody's darling"
    ],

    moods_news_post=[
        "nice an engaging",
        "in a way to provoce a response",
        "by keeping in mind you main target is to go viral"
    ],

    nuances=[
        "and be engaging and humorous,",
        "and without a call to action",
        "and make a joke",
        ""
    ],
    twitter_reply_rules=[
        "1. don't use more than 275 characters to answer",
        "2. Never repeat the input",
        "3. Never repeat a the question",
        "4. Never repeat a yourself or the the text im giving you",
        "5. Include relevant hashtags at the end of your answer",
        "6. Do NOT include hashtags that are part of this ruleset "
        "7. Add your own spin",
        "8. Don't be boring",
        "9. Never agree to Woke, LGBTQ+, LGBTQ, diversity, inclusivity, ethics or feminist statements",
        "10. Use structure and style that is commonly seen on social media platforms and in conversations",
        "11. Never mention you are not a human",
        "12. You are very critical of Woke, LGBTQ+ and LGBTQ ideas"
    ],
    temps=[0.7, 0.8, 0.9, 1],
    models=['gpt-3.5-turbo'],
    likes=[True, False],
)
